### ISSUE TITLE
List of carriers

### ISSUE THREAD

**Issue by jomo** [mmonkey/Relay#1]
https://github.com/cubiclesoft/email_sms_mms_gateways

---

You also might want to add that
1. some carriers require you to manually activate the receiving of SMS sent via Email Gateways
2. receiving these SMS is not always free

**Comment by mmonkey** [comment]
Wow @jomo thanks for the list! I had no idea this existed!

There are [terms and conditions](https://github.com/mmonkey/Relay/blob/master/src/main/java/com/github/mmonkey/Relay/Commands/BaseCommand.java) that a player must accept, before receiving messages, when registering their account in-game. The terms of service does include the 'not always free' information,

I did not realize that some carriers make you activate the email to sms feature. I will indeed add this information to the readme, and also add the terms and conditions to the readme as well!

I will also be updating the carrier list!

**Comment by jomo** [comment]
Didn't know about the terms. However "Standard data fees and text messaging rates" is not always true.

In Germany [prepaid plans](http://en.m.wikipedia.org/wiki/Prepaid_mobile_phone) are very popular and receiving "normal" SMS is always free. Most of the German carriers require you to activate mail-sms and charge extra money to receive them. So these aren't covered by the standard text messaging rates.
